### ISSUE TITLE
[Clarification Request] URIs in examples

### ISSUE THREAD

**Issue by JonTheNiceGuy** [PaulKinlan/WebIntents#64]
Can you confirm whether the following example requires the use of the webintents.org URI:

var intent = new Intent("http://webintents.org/share", "text/uri-list", "http://news.bbc.co.uk");

Could I instead use:

var intent = new Intent("http://MyOwnDomain.TLD/share", "text/uri-list", "http://news.bbc.co.uk");

Is this URI stating the action "share" (in much the same way as the XML DTDs provide a URI) or is it requesting code from that URI?

**Comment by JonTheNiceGuy** [comment]
D'oh. Ignore the question... Navigated to the page and it defines the action by explaining it!

**Comment by PaulKinlan** [comment]
The URI can be anything you want. It is used to resolve the services that
say they support that intent. So two different URIs are two different
intents. Xyz.com/share is different from webintents.org/share

No information from the URI is pulled in.

It is a URI because it points to a place on the internet or local network
where the documentation for the intent is held.
On Aug 9, 2011 9:43 AM, "JonTheNiceGuy" <
reply@reply.github.com>
wrote:
