### ISSUE TITLE
Content-disposition: Prototype

### ISSUE THREAD

**Issue by PaulKinlan** [PaulKinlan/WebIntents#89]
We need to provide a way for the service to indicate how it will be opened by the system.  Will it run inline, will it run in a new context or will it run in the background.

**Comment by seaneagan** [comment]
Content disposition choice is a great idea, and definitely needed, however, I believe users, not services, should make this choice, via their chosen web intents implementation (browser), and client (calling webpage, see #80), and even their whims (as with "open link in new tab") where possible.

Services should merely be informed of their disposition, so they can [respond](http://www.alistapart.com/articles/responsive-web-design/) to it, which is already taken care of by media queries etc.

It might be useful to allow services to provide content disposition _preferences_ though, in order to help users, browsers, and search engines rank services for given scenarios, however, this seems relevant to all services, not just those that implement web intents actions.

**Comment by PaulKinlan** [comment]
There are a whole swath of services that are never designed to be used in anything other than the intended methods of the developer.  Would you a user want a twitter web intent (i.e, their current implementation) to open in a full on window?  I don't think they would.  And by presenting users with more and more options it introduces an impedance in using the service.

That being said, I am thinking out aloud here and it should be discussed more.

**Comment by seaneagan** [comment]
I think the web platform already has support for dealing with unsupported content dispositions.  Browsing contexts can generally detect various aspects of their disposition, and if they don't support it, they either notify the user, attempt to resolve it such as by popping out of an iframe, or ignore it and display a UI not optimized for that disposition.

Let's compare some existing content dispositions in the context of web intents:
- dialog (popup window)
  - some context retained since client is (at least initially) visible in background
  - context lost if user switches to another task before completing the action
  - not available on small screens / mobile devices
  - limited/arbitrary available space
  - arbitrary placement
- new tab
  - maximal available space
  - some context loss due to client no longer being displayed
- embedded
  - maximal context retention
  - limited space
  - potential style clash between client and service
  - potential security issues when implemented with iframes or injected html, though see #80 for a secure implementation.
- fullscreen
  - useful for video services
- background
  - minimal intrusion / distraction to the user
  - doesn't make sense for actions requiring user interaction.
  - services would need to depend on clients (whom they cannot identify and thus cannot trust), or possibly the browser, to inform the user about events related to the action.
  - If user selects a default service for an action with a background disposition, they will not be informed whatsoever of the action, unless the browser notifies them somehow.
- notification
  - services could be displayed in [web notifications](http://www.w3.org/TR/notifications/).
  - could display icon / title of client in notification bar to retain some context.
- panel (as seen in chrome os)
  - solves many issues mentioned for popups
  - not yet (ever?) available on all platforms
  - won't work on small screens

Also, sometimes users are allowed to switch between dispositions anyways:
- [fullscreen <-> embedded](http://peter.sh/2011/01/javascript-full-screen-api-navigation-timing-and-repeating-css-gradients/)
- [panel <-> tab](http://code.google.com/p/chromium-os/issues/detail?id=14624)
- background <-> foreground

An "inline" disposition doesn't seem to work in the context of "default actions", since the action picker is never shown.

The optimal content disposition for a given activity seems to depend on:
- The amount of visual space needed for the activity
- The likely duration of the activity
  - For shorter activities, context retention is important, for longer activities, being out of the way is important
- Whether the action involves any user participation at all, otherwise "background" may work.
- Which dispositions make sense / are available on a given device / platform
- Client's preference.
- User's preference.

Services can't possibly know all of this up front.  Browsers however will know much more when they are actually loading an activity, such as the user's identity, their preferences / history, and details about the device and platform they are operating on, and thus can at least make an educated guess.  Client likely know additional information about the activity, and thus might have useful input as to the disposition.  Sometimes though, these guesses will be wrong, and user's should be able to specify their _intent_, since that's what we're after in the first place.

**Comment by PaulKinlan** [comment]
http://groups.google.com/group/web-intents (we might want to talk about it there also as there are a lot of contexts that we haven't got yet nailed down)
